name: Project Pipeline

on: [push]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract Python version
        id: extract-python-version
        run: |
          PYTHON_VERSION=$(grep -oP '(?<=python = ")[^"]*' pyproject.toml)
          echo "::set-output name=python-version::$PYTHON_VERSION"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ steps.extract-python-version.outputs.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pylint
        run: pylint **/*.py

      - name: Check Python formatting with Black
        run: black --check .

      - name: Strip Output from Jupyter Notebooks
        run: nbstripout .
